version: 2

models:
  - name: fct_orders
    description: "The central fact table for all Olist orders."
    columns:
      - name: order_id
        description: "The unique identifier for an order."
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: "Foreign key to the customers dimension table."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

      - name: payment_value
        description: "The total value paid for the order."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                # No max value

  - name: dim_customers
    description: "The dimension table for customers."
    columns:
      - name: customer_id
        description: "The unique identifier for a customer."
        tests:
          - unique
          - not_null